image: atlassian/default-image:2

pipelines:
  tags:
    '*':
      - step:
          script:
            - apt update && apt -y install python-pip
            - pip install awscli
            - docker login -u ${DOCKER_USER} -p ${DOCKER_PASS}
            - docker build -t ${REPO}:${BITBUCKET_TAG} .
            - docker push ${REPO}:${BITBUCKET_TAG}
          services:
            - docker
