image: atlassian/default-image:2

pipelines:
  # Branches get an image tagged for them with the code from the last commit. Staging tag is for use in staging environments, production tag is for production environments, etc...
  branches:
    '{dev,staging,master,pipelines}':
      - step:
          script:
            - apt update && apt -y install python-pip
            - pip install awscli
            - $(aws ecr get-login --no-include-email --region ${AWS_REGION})
            - docker build -t ${ECR_REPO}:${BITBUCKET_BRANCH} .
            - docker push ${ECR_REPO}:${BITBUCKET_BRANCH}
          services:
            - docker
  tags:
    '*':
      - step:
          script:
            - apt update && apt -y install python-pip
            - pip install awscli
            - $(aws ecr get-login --no-include-email --region ${AWS_REGION})
            - docker build -t ${ECR_REPO}:${BITBUCKET_TAG} .
            - docker push ${ECR_REPO}:${BITBUCKET_TAG}
          services:
            - docker
